---
- name: Set initial password
  block:
    - name: Generate authorization string for "{{ nutanix_prism_pwd_host }}"
      set_fact:
        nutanix_prism_pwd_auth_string: "{{ nutanix_prism_pwd_username }}:{{ nutanix_prism_initial_password }}"
      no_log: True

    - name: Generate authorization header for "{{ nutanix_prism_eula_host }}"
      set_fact:
        nutanix_prism_pwd_api_auth: "Basic {{ nutanix_prism_pwd_auth_string | b64encode(encoding='ascii') }}"
      no_log: True

    - name: Set Prism Central "admin" user password
      uri:
        url: "https://{{ nutanix_prism_pwd_host }}:{{ nutanix_prism_pwd_port }}/PrismGateway/services/rest/v1/utils/change_default_system_password"
        method: POST
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body:
          oldPassword: "{{ nutanix_prism_initial_password }}"
          newPassword: "{{ nutanix_prism_new_password }}"
        headers:
          Authorization: "{{ nutanix_prism_pwd_api_auth }}"
        status_code: 200
        return_content: yes
      register: nutanix_prism_pwd_change
      ignore_errors: no

    - debug:
        var: nutanix_prism_pwd_change
      when: nutanix_debug

    - ansible.builtin.fail:
        msg: "'{{ nutanix_prism_pwd_username }}' initial account password change failed."
      when:
        - not nutanix_prism_pwd_change.json.value
